server:
  port: 8000

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://43.200.160.0.nip.io:8761/eureka
