server:
  port: 8000

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
    
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: backend-service-api-route
              uri: lb://backend-service
              predicates:
                - Path=/api/backend/**
              filters:
                - RewritePath=/api/backend/(?<segment>.*), /${segment}
                
            - id: backend-service-docs-route
              uri: lb://backend-service
              predicates:
                - Path=/api-docs/backend/v3/api-docs
              filters:
                - RewritePath=/api-docs/backend/(?<segment>.*), /${segment}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://129.154.54.225:8761/eureka

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: backend-service
        url: /api-docs/backend/v3/api-docs
