name: gateway-service dev CD 파이프라인

on:
  workflow_run:
    workflows: ["gateway-service CI pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read

    steps:
      - name: Docker 이미지 dev 서버 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEV_HOST}}
          username: ${{secrets.DEV_USERNAME}}
          key: ${{secrets.DEV_KEY}}
          script: |
            cd /home/ubuntu
            docker rm -f gateway-service-dev || true
            docker compose pull gateway-service-dev
            docker compose up -d --no-deps --force-recreate --pull always gateway-service-dev
            docker image prune -f
